import { createContext, useContext } from "react";

export type Lang = "es" | "en";

export const T: Record<Lang, Record<string, string>> = {
  es: {
    dashboard: "DASHBOARD", alerts: "ALERTAS", events: "EVENTOS", threatIntel: "THREAT INTEL",
    sentinelAi: "SENTINEL AI", agents: "AGENTES", rules: "REGLAS", settings: "CONFIGURACIÓN",
    welcome: "Bienvenido", logout: "Cerrar sesión", login: "INICIAR SESIÓN",
    user: "Usuario", password: "Contraseña", invalidCreds: "Credenciales inválidas",
    hint: "Prueba: nadia/1234 o admin/admin",
    totalAlerts: "Alertas Totales", critical: "Críticas", activeAgents: "Agentes Activos", eventsHour: "Eventos/hora",
    alerts24h: "ALERTAS (24H)", severity: "SEVERIDAD",
    realTimeAlerts: "Alertas en Tiempo Real", securityEvents: "Eventos de Seguridad",
    time: "Hora", source: "Origen", destination: "Destino", type: "Tipo",
    appearance: "MODO DE APARIENCIA", dark: "Oscuro", light: "Claro",
    userMgmt: "GESTIÓN DE USUARIOS", newUser: "Nuevo usuario", createUser: "Crear Usuario",
    agentInstaller: "INSTALADOR DE AGENTE", downloadInstaller: "Descargar Instalador (.bat)",
    changePassword: "CAMBIAR CONTRASEÑA", currentPass: "Contraseña actual", newPass: "Nueva contraseña",
    confirmPass: "Confirmar contraseña", updatePass: "Actualizar Contraseña",
    language: "IDIOMA", aiConfig: "CONFIGURACIÓN IA", recentAnalysis: "ANÁLISIS RECIENTE",
    userCreated: "Usuario creado", passUpdated: "Contraseña actualizada",
    passMismatch: "Las contraseñas no coinciden", wrongCurrentPass: "Contraseña actual incorrecta",
    rulesTitle: "Reglas de Detección", ruleId: "ID Regla", ruleDesc: "Descripción", ruleLevel: "Nivel",
    ruleGroup: "Grupo", ruleStatus: "Estado", addRule: "Agregar Regla", enabled: "Activa", disabled: "Inactiva",
    ruleName: "Nombre de la regla", ruleCondition: "Condición", save: "Guardar",
    editRule: "Editar", deleteRule: "Eliminar", confirmDelete: "¿Eliminar esta regla?",
    actions: "Acciones", cancel: "Cancelar", update: "Actualizar",
    backToRules: "Volver a Reglas", ruleDetails: "Detalle de Regla",
    ruleEnabled: "Regla Activa", ruleDisabled: "Regla Inactiva",
    exportJson: "Exportar JSON", exportAll: "Exportar Todas",
    xmlSource: "Fuente XML", decodedAs: "Decoded As", match: "Match",
    ifSid: "If SID", frequency: "Frecuencia", timeframe: "Timeframe", options: "Opciones",
  },
  en: {
    dashboard: "DASHBOARD", alerts: "ALERTS", events: "EVENTS", threatIntel: "THREAT INTEL",
    sentinelAi: "SENTINEL AI", agents: "AGENTS", rules: "RULES", settings: "SETTINGS",
    welcome: "Welcome", logout: "Logout", login: "LOG IN",
    user: "Username", password: "Password", invalidCreds: "Invalid credentials",
    hint: "Try: nadia/1234 or admin/admin",
    totalAlerts: "Total Alerts", critical: "Critical", activeAgents: "Active Agents", eventsHour: "Events/hour",
    alerts24h: "ALERTS (24H)", severity: "SEVERITY",
    realTimeAlerts: "Real-Time Alerts", securityEvents: "Security Events",
    time: "Time", source: "Source", destination: "Destination", type: "Type",
    appearance: "APPEARANCE MODE", dark: "Dark", light: "Light",
    userMgmt: "USER MANAGEMENT", newUser: "New user", createUser: "Create User",
    agentInstaller: "AGENT INSTALLER", downloadInstaller: "Download Installer (.bat)",
    changePassword: "CHANGE PASSWORD", currentPass: "Current password", newPass: "New password",
    confirmPass: "Confirm password", updatePass: "Update Password",
    language: "LANGUAGE", aiConfig: "AI CONFIGURATION", recentAnalysis: "RECENT ANALYSIS",
    userCreated: "User created", passUpdated: "Password updated",
    passMismatch: "Passwords don't match", wrongCurrentPass: "Wrong current password",
    rulesTitle: "Detection Rules", ruleId: "Rule ID", ruleDesc: "Description", ruleLevel: "Level",
    ruleGroup: "Group", ruleStatus: "Status", addRule: "Add Rule", enabled: "Enabled", disabled: "Disabled",
    ruleName: "Rule name", ruleCondition: "Condition", save: "Save",
    editRule: "Edit", deleteRule: "Delete", confirmDelete: "Delete this rule?",
    actions: "Actions", cancel: "Cancel", update: "Update",
    backToRules: "Back to Rules", ruleDetails: "Rule Details",
    ruleEnabled: "Rule Enabled", ruleDisabled: "Rule Disabled",
    exportJson: "Export JSON", exportAll: "Export All",
    xmlSource: "XML Source", decodedAs: "Decoded As", match: "Match",
    ifSid: "If SID", frequency: "Frequency", timeframe: "Timeframe", options: "Options",
  },
};

export const LangContext = createContext<{ t: Record<string, string>; lang: Lang }>({ t: T.es, lang: "es" });
export const useLang = () => useContext(LangContext);
